// Style Profile store for Phase 3
// Persists quiz results, AI persona, color preferences.
// partialize applied: only domain data (not UI state)

import { create } from "zustand";
import { persist } from "zustand/middleware";

export interface StyleProfileStore {
  persona: string | null; // e.g. "romantic", "minimalist", "bold"
  favoriteColors: string[];
  avoidedColors: string[];
  preferredStyles: string[];
  preferredFits: string[];
  favoriteBrands: string[];
  avoidedMaterials: string[];
  priceRange: { min: number; max: number } | null;
  occasions: string[];

  colorPalette: string[] | null; // Generated by AI
  aestheticScore: number | null;
  bodyType: string | null;

  setPersona: (persona: string) => void;
  setFavoriteColors: (colors: string[]) => void;
  addPreferredStyle: (style: string) => void;
  setPriceRange: (min: number, max: number) => void;
  setBodyType: (bodyType: string) => void;
  setColorPalette: (palette: string[]) => void;
  setAestheticScore: (score: number) => void;
  reset: () => void;
}

export const useStyleProfileStore = create<StyleProfileStore>()(
  persist(
    (set) => ({
      persona: null,
      favoriteColors: [],
      avoidedColors: [],
      preferredStyles: [],
      preferredFits: [],
      favoriteBrands: [],
      avoidedMaterials: [],
      priceRange: null,
      occasions: [],

      colorPalette: null,
      aestheticScore: null,
      bodyType: null,

      setPersona: (persona) => set({ persona }),
      setFavoriteColors: (favoriteColors) => set({ favoriteColors }),
      addPreferredStyle: (style) =>
        set((state) => ({
          preferredStyles: [...state.preferredStyles, style],
        })),
      setPriceRange: (min, max) => set({ priceRange: { min, max } }),
      setBodyType: (bodyType) => set({ bodyType }),
      setColorPalette: (colorPalette) => set({ colorPalette }),
      setAestheticScore: (aestheticScore) =>
        set({ aestheticScore: Math.min(1, Math.max(0, aestheticScore)) }),
      reset: () =>
        set({
          persona: null,
          favoriteColors: [],
          preferredStyles: [],
          colorPalette: null,
          aestheticScore: null,
        }),
    }),
    {
      name: "luxeverse-style-profile",
      partialize: (state) => ({
        persona: state.persona,
        favoriteColors: state.favoriteColors,
        preferredStyles: state.preferredStyles,
        priceRange: state.priceRange,
        occasions: state.occasions,
        colorPalette: state.colorPalette,
        aestheticScore: state.aestheticScore,
        bodyType: state.bodyType,
      }),
    }
  )
);
